#!/usr/bin/env bash
# generated by lazyvim-offline installer
# nvim 启动包装器：把离线包自带的工具与个人 ~/.local/bin 置于 PATH 最前，
# 保证 mason 中依赖 node 的工具(pyright 等)使用离线包内的 node，
# 并隔离内网机器上可能存在的旧/脏依赖。
PREFIX="__INSTALL_PREFIX__"

export PATH="$PREFIX/tools/bin:$HOME/.local/bin:$PATH"

mkdir -p "${XDG_DATA_HOME:-$HOME/.local/share}/nvim" \
         "${XDG_CONFIG_HOME:-$HOME/.config}/nvim" \
         "${XDG_STATE_HOME:-$HOME/.local/state}/nvim" \
         "${XDG_CACHE_HOME:-$HOME/.cache}/nvim" 2>/dev/null || true

exec "$PREFIX/nvim/bin/nvim" "$@"
